app/src/VersionControl/GitControlBundle/Entity/Issue.php
<?php
/*
 * This file is part of the GitControlBundle package.
 *
 * (c) Paul Schweppe <paulschweppe@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VersionControl\GitControlBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use VersionControl\GitControlBundle\Entity\Issues\IssueInterface;

/**
 * Issue.
 *
 * @ORM\Table(name="issue", indexes={@ORM\Index(name="fk_issue_ver_user1_idx", columns={"ver_user_id"}), @ORM\Index(name="fk_issue_project1_idx", columns={"project_id"}), @ORM\Index(name="fk_issue_issue_milestone1_idx", columns={"issue_milestone_id"})})
 * @ORM\Entity(repositoryClass="VersionControl\GitControlBundle\Repository\IssueRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Issue implements IssueInterface
{
    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=45, nullable=true)
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="closed_at", type="datetime", nullable=true)
     */
    private $closedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var int
     *
     * @ORM\Column(name="github_number", type="integer", nullable=true)
     */
    private $githubNumber;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \VersionControl\GitControlBundle\Entity\IssueMilestone
     *
     * @ORM\ManyToOne(targetEntity="VersionControl\GitControlBundle\Entity\IssueMilestone")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="issue_milestone_id", referencedColumnName="id")
     * })
     */
    private $issueMilestone;

    /**
     * @var \VersionControl\GitControlBundle\Entity\Project
     *
     * @ORM\ManyToOne(targetEntity="VersionControl\GitControlBundle\Entity\Project")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     * })
     */
    private $project;

    /**
     * @var \VersionControl\GitControlBundle\Entity\User\User
     *
     * @ORM\ManyToOne(targetEntity="VersionControl\GitControlBundle\Entity\User\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="ver_user_id", referencedColumnName="id")
     * })
     */
    private $verUser;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="VersionControl\GitControlBundle\Entity\IssueLabel", inversedBy="issue")
     * @ORM\JoinTable(name="issue_has_issue_label",
     *   joinColumns={
     *     @ORM\JoinColumn(name="issue_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="issue_label_id", referencedColumnName="id")
     *   }
     * )
     */
    private $issueLabel;

    /**
     * Issue comments.
     *
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="VersionControl\GitControlBundle\Entity\IssueComment", mappedBy="issue", fetch="EXTRA_LAZY")
     */
    private $issueComments;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->issueLabel = new \Doctrine\Common\Collections\ArrayCollection();
        $this->issueComments = new \Doctrine\Common\Collections\ArrayCollection();
        $this->setCreatedAt(new \DateTime());
        $this->setStatus('open');
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return Issue
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Issue
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set status.
     *
     * @param string $status
     *
     * @return Issue
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set closedAt.
     *
     * @param \DateTime $closedAt
     *
     * @return Issue
     */
    public function setClosedAt($closedAt)
    {
        $this->closedAt = $closedAt;

        return $this;
    }

    /**
     * Get closedAt.
     *
     * @return \DateTime
     */
    public function getClosedAt()
    {
        return $this->closedAt;
    }

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return Issue
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt.
     *
     * @param \DateTime $updatedAt
     *
     * @return Issue
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set githubNumber.
     *
     * @param int $githubNumber
     *
     * @return Issue
     */
    public function setGithubNumber($githubNumber)
    {
        $this->githubNumber = $githubNumber;

        return $this;
    }

    /**
     * Get githubNumber.
     *
     * @return int
     */
    public function getGithubNumber()
    {
        return $this->githubNumber;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set issueMilestone.
     *
     * @param \VersionControl\GitControlBundle\Entity\IssueMilestone $issueMilestone
     *
     * @return Issue
     */
    public function setIssueMilestone(\VersionControl\GitControlBundle\Entity\IssueMilestone $issueMilestone = null)
    {
        $this->issueMilestone = $issueMilestone;

        return $this;
    }

    /**
     * Get issueMilestone.
     *
     * @return \VersionControl\GitControlBundle\Entity\IssueMilestone
     */
    public function getIssueMilestone()
    {
        return $this->issueMilestone;
    }

    /**
     * Set project.
     *
     * @param \VersionControl\GitControlBundle\Entity\Project $project
     *
     * @return Issue
     */
    public function setProject(\VersionControl\GitControlBundle\Entity\Project $project = null)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project.
     *
     * @return \VersionControl\GitControlBundle\Entity\Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Set verUser.
     *
     * @param \VersionControl\GitControlBundle\Entity\User\User $verUser
     *
     * @return Issue
     */
    public function setVerUser(\VersionControl\GitControlBundle\Entity\User\User $verUser = null)
    {
        $this->verUser = $verUser;

        return $this;
    }

    /**
     * Get User.
     *
     * @return \VersionControl\GitControlBundle\Entity\Issues\IssueUserInterface
     */
    public function getUser()
    {
        return $this->verUser;
    }

    /**
     * Get verUser.
     *
     * @return \VersionControl\GitControlBundle\Entity\User\User
     */
    public function getVerUser()
    {
        return $this->verUser;
    }

    /**
     * Add issueLabel.
     *
     * @param \VersionControl\GitControlBundle\Entity\IssueLabel $issueLabel
     *
     * @return Issue
     */
    public function addIssueLabel(\VersionControl\GitControlBundle\Entity\Issues\IssueLabel $issueLabel)
    {
        $this->issueLabel[] = $issueLabel;

        return $this;
    }

    /**
     * Remove issueLabel.
     *
     * @param \VersionControl\GitControlBundle\Entity\IssueLabel $issueLabel
     */
    public function removeIssueLabel(\VersionControl\GitControlBundle\Entity\Issues\IssueLabel $issueLabel)
    {
        $this->issueLabel->removeElement($issueLabel);
    }

    /**
     * Get issueLabel.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIssueLabel()
    {
        return $this->issueLabel;
    }

    /**
     * Get Issue Comments.
     *
     * @return \Doctrine\Common\Collections\Collection of \VersionControl\GitControlBundle\Entity\IssueComment
     */
    public function getIssueComments()
    {
        return $this->issueComments;
    }

    /**
     * Set Issue Comments.
     *
     * @param \Doctrine\Common\Collections\Collection $issueComments
     *
     * @return \VersionControl\GitControlBundle\Entity\Issue
     */
    public function setIssueComments(array $issueComments)
    {
        $this->issueComments = $issueComments;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateModifiedDatetime()
    {

app/src/VersionControl/GitControlBundle/Entity/Issues/IssueCommentInteface.php
<?php
/*
 * This file is part of the GitControlBundle package.
 *
 * (c) Paul Schweppe <paulschweppe@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VersionControl\GitControlBundle\Entity\Issues;

/**
 * IssueComment.
 */
interface IssueCommentInteface
{
    /**
     * Set comment.
     *
     * @param string $comment
     *
     * @return IssueComment
     */
    public function setComment($comment);

    /**
     * Get comment.
     *
     * @return string
     */
    public function getComment();

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return IssueComment
     */
    public function setCreatedAt($createdAt);

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt();

    /**
     * Set updatedAt.
     *
     * @param \DateTime $updatedAt
     *
     * @return IssueComment
     */
    public function setUpdatedAt($updatedAt);

    /**
     * Get updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt();

    /**
     * Get id.
     *
     * @return int
     */
    public function getId();

    /**
     * Gets issue.
     *
     * @return \VersionControl\GitControlBundle\Entity\Issues\IssueInterface
     */
    public function getIssue();

    /**
     * Gets Createor of comment.
     *
     * @return \VersionControl\GitControlBundle\Entity\Issues\IssueUserInterface
     */
    public function getUser();
}

app/src/VersionControl/GitControlBundle/Entity/Issues/IssueLabelInterface.php
<?php
/*
 * This file is part of the GitControlBundle package.
 *
 * (c) Paul Schweppe <paulschweppe@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VersionControl\GitControlBundle\Entity\Issues;

/**
 * IssueLabel.
 */
interface IssueLabelInterface
{
    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle();

    /**
     * Get hexColor.
     *
     * @return string
     */
    public function getHexColor();

    /**
     * Get id.
     *
     * @return int
     */
    public function getId();

    /**
     * Get issue.
     *
     * @return array
     */
    public function getIssues();
}

app/src/VersionControl/GitControlBundle/Form/IssueMilestoneType.php
<?php
/*
 * This file is part of the GitControlBundle package.
 *
 * (c) Paul Schweppe <paulschweppe@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VersionControl\GitControlBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Lrotherfield\Component\Form\Type\HiddenEntityType;

class IssueMilestoneType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            //->add('dueOn')
            ->add('dueOn', DateTimeType::class, array('date_widget' => 'single_text', 'time_widget' => 'single_text', 'required' => false))

            ->add('project', HiddenEntityType::class, array(
                    'class' => 'VersionControl\GitControlBundle\Entity\Project',
                ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function configureOptions(OptionsResolver  $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'VersionControl\GitControlBundle\Entity\IssueMilestone',
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'versioncontrol_gitcontrolbundle_issuemilestone';
    }
}

app/src/VersionControl/GitControlBundle/Form/IssueType.php
<?php
/*
 * This file is part of the GitControlBundle package.
 *
 * (c) Paul Schweppe <paulschweppe@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace VersionControl\GitControlBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use VersionControl\GitControlBundle\Repository\IssueMilestoneRepository;
//use VersionControl\GitControlBundle\Repository\IssueLabelRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Lrotherfield\Component\Form\Type\HiddenEntityType;

class IssueType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $project = $builder->getData()->getProject();
        $builder
            ->add('title')
            ->add('description')
            //->add('status')
            //->add('closedAt')
            //->add('createdAt')
            //->add('updatedAt')
            //->add('githubNumber')
            ->add('issueMilestone', EntityType::class, array(
                    'multiple' => false,   // Multiple selection allowed
                    //'expanded' => true,   // Render as checkboxes
                    'placeholder' => 'Choose a milestone',
                    'required' => false,
                    'property' => 'title', // Assuming that the entity has a "name" property
                    'class' => 'VersionControl\GitControlBundle\Entity\IssueMilestone',
                    'query_builder' => function (IssueMilestoneRepository $er) use ($project) {
                        return $er->createQueryBuilder('a')
                            ->where('a.project = :project')
                            ->setParameter('project', $project)
                            ->orderBy('a.id', 'ASC');
                    },
                ))
            ->add('project', HiddenEntityType::class, array(
                    'class' => 'VersionControl\GitControlBundle\Entity\Project',
                ))
            //->add('verUser')
            ->add('issueLabel', EntityType::class, array(
                    'multiple' => true,   // Multiple selection allowed
                    'expanded' => true,   // Render as checkboxes
                    'property' => 'title', // Assuming that the entity has a "name" property
                    'class' => 'VersionControl\GitControlBundle\Entity\IssueLabel',
                    'required' => false,
                    'query_builder' => function (EntityRepository $er) use ($project) {
                        return $er->createQueryBuilder('a')
                            ->where('a.project = :project OR a.allProjects = 1')
                            ->setParameter('project', $project)
                            ->orderBy('a.id', 'ASC');
                    },
                ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'VersionControl\GitControlBundle\Entity\Issue',
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'versioncontrol_gitcontrolbundle_issue';
    }
}

app/src/VersionControl/GitControlBundle/Resources/views/Issues/IssueMilestone/edit.html.twig
{% extends "VersionControlGitControlBundle::admincontent.layout.html.twig" %}


{% block topnavleft %}
    {% include 'VersionControlGitControlBundle::Partials/projectEnvironments.html.twig'  %}
{% endblock %}
            
{% block header %}
    
    
    <h1 class="page-header">
        Edit Milestone #{{milestone.id}} : {{milestone.title}}
        <small>{{ project.title }}
            {% if (is_granted('MASTER', project)) %}
                (<span class="edit"><a href="{{ path('project_edit', { 'id': project.id }) }}" class="non-ajax">edit</a></span>)
            {% endif %}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ path('home')}}"><i class="fa fa-product-hunt"></i> Projects</a>
        </li>
        <li >
            <i class="fa fa-bug"></i> <a href="{{path('issues', { 'id': project.id }) }}">Issues</a>
        </li>
        <li class="active">
                <i class="fa fa-file"></i> Milestones
            </li>
    </ol>
{% endblock %}

{% block sidemenu -%}
 {% include 'VersionControlGitControlBundle::Partials/sidemenu.html.twig'  %}
{% endblock %}

{% block content -%}

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">
                <i class="fa fa-bug fa-fw"></i> Edit Milestone
            </h3>
        </div>
        <div class="box-body">
 
                {{ form(edit_form) }}
                
        </div>
    </div>
{% endblock %}

app/src/VersionControl/GitControlBundle/Resources/views/Issues/IssueMilestone/milestonesIssues.html.twig
<div class="row">
        <div class="col-md-12">
             <form action="{{ path('issuemilestone_show', { 'milestoneId': issueMilestone.id, 'id': project.id }) }}" method="GET">
                <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search..." name="{{keywordParamaterName}}">
                        <span class="input-group-btn">
                          <button class="btn btn-default" type="submit">Go!</button>
                        </span>
                 </div><!-- /input-group -->
             </form>
        </div>
    </div>

    <div class="list-group spacer-top">
        {% if(pagination|length > 0) %}
            {% for issue in pagination %}
               <div class="list-group-item">
                   <div class="row">
                       <div class="col-md-10">
                           <strong class="str-truncated"><a href="{{ path('issue_show', { 'id':project.id, 'issueId': issue.id }) }}">{{ issue.title }}</a></strong>
                       </div>
                       <div class="col-md-2">
                           <i class="fa fa-comment-o fa-fw"></i>{{issue.issueComments|length}}
                       </div>
                   </div>
                   {% if(issue.issueLabel|length > 0) %}
                       <div class="row">
                            <div class="col-md-10">
                               {% for label in issue.issueLabel %}
                                   <div style="background-color:#{{ label.hexColor }};" class="issue-label btn-xs">
                                       <a href="" style="color:#{{label.hexColor|textcolor}};">
                                            <i class="fa fa-tag fa-fw"></i>
                                           {{ label.title }}
                                       </a>
                                   </div>
                               {% endfor %}
                           </div>
                       </div>
                   {% endif %}
                   <div class="row">
                       <div class="col-md-10">
                           <small>#{{issue.id}} opened by {{issue.user.name}} {{issue.createdAt|time_ago_in_words}}</small>
                       </div>
                       <div class="col-md-2">
                           .
                       </div>
                   </div>
               </div>

           {% endfor %}
        {% else %}
            {% if(keyword) %}
                <p>There are no {{status}} issues for this search string. Please try a different search.</p>
            {% else %}
                <div class="list-group-item">
                    <p>There are no {{status}} issues for this milestone</p>
                </div>
            {% endif %}
        {% endif %}
    </div>
    <div class="count">
        {{ pagination.getTotalItemCount }}
    </div>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>

app/src/VersionControl/GitControlBundle/Resources/views/Issues/IssueMilestone/new.html.twig
{% extends "VersionControlGitControlBundle::admincontent.layout.html.twig" %}


{% block topnavleft %}
    {% include 'VersionControlGitControlBundle::Partials/projectEnvironments.html.twig'  %}
{% endblock %}
            
{% block header %}
    
    
    <h1 class="page-header">
        New Milestone
        <small>{{ project.title }}
            {% if (is_granted('MASTER', project)) %}
                (<span class="edit"><a href="{{ path('project_edit', { 'id': project.id }) }}" class="non-ajax">edit</a></span>)
            {% endif %}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ path('home')}}"><i class="fa fa-product-hunt"></i> Projects</a>
        </li>
        <li >
            <i class="fa fa-bug"></i> <a href="{{path('issues', { 'id': project.id }) }}">Issues</a>
        </li>
        <li class="active">
                <i class="fa fa-file"></i> New Milestone
            </li>
    </ol>
{% endblock %}

{% block sidemenu -%}
 {% include 'VersionControlGitControlBundle::Partials/sidemenu.html.twig'  %}
{% endblock %}

{% block content -%}

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">
                <i class="fa fa-bug fa-fw"></i> New Milestone
            </h3>
        </div>
        <div class="box-body">
  
                {{ form_start(form,{ 'attr': { 'class': 'form'}}) }}

                    {{ form_errors(form) }} 
                
                <div class="form-group">
                    {{ form_label(form.title) }}
                    {{ form_errors(form.title) }}
                    {{ form_widget(form.title,{ 'attr': { 'class': 'form-control', 'placeholder':'Please a remote server'}}) }}
                </div>
                
                <div class="form-group">
                    {{ form_label(form.description) }}
                    {{ form_errors(form.description) }}
                    {{ form_widget(form.description,{ 'attr': { 'class': 'form-control', 'placeholder':'Please a remote server'}}) }}
                </div>
                
                <div class="form-group">
                    {{ form_label(form.dueOn) }}
                    {{ form_errors(form.dueOn) }}
                    {{ form_widget(form.dueOn) }}
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                           <a href="{{ path('issuemilestones',{ 'id': project.id }) }}" class="btn btn-default">
                               Cancel
                           </a>
                           {{ form_widget(form.submit, { 'attr': {'class': ' btn-success submit'} }) }}
                    </div>
                </div>
                {{ form_end(form)}}

        </div>
    </div>
{% endblock %}

app/src/VersionControl/GitControlBundle/Resources/views/Issues/IssueMilestone/show.html.twig
{% extends "VersionControlGitControlBundle::admincontent.layout.html.twig" %}


{% block topnavleft %}
    {% include 'VersionControlGitControlBundle::Partials/projectEnvironments.html.twig'  %}
{% endblock %}
            
{% block header %}
    
    
    <h1 class="page-header">
        Milestone #{{ entity.id }}: {{ entity.title }}
        <small>{{ project.title }}
            {% if (is_granted('MASTER', project)) %}
                (<span class="edit"><a href="{{ path('project_edit', { 'id': project.id }) }}" class="non-ajax">edit</a></span>)
            {% endif %}
        </small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ path('home')}}"><i class="fa fa-product-hunt"></i> Projects</a>
        </li>
        <li >
            <i class="fa fa-bug"></i> <a href="{{path('issues', { 'id': project.id }) }}">Issues</a>
        </li>
        <li class="active">
                <i class="fa fa-file"></i> {{ entity.title }} 
            </li>
    </ol>
{% endblock %}

{% block sidemenu -%}
 {% include 'VersionControlGitControlBundle::Partials/sidemenu.html.twig'  %}
{% endblock %}

{% block content -%}
    
    <div class="box box-primary">
        <div class="box-header with-border">
  
            <h3 class="box-title">
                <div class="issue-state issue-state-{{ entity.state }}"> 
                    {{ entity.state|capitalize }} 
                </div>
                    <strong>{% if(entity.user is null)%}{%else%}{{entity.user.name}}{%endif%}</strong> created this Milestone {{ entity.createdAt|time_ago_in_words }}

            </h3>

             <div class="box-tools">
                {% if(entity.closed)%}
                    <a href="{{ path('issuemilestone_open',{ 'id': project.id,'milestoneId': entity.id  }) }}" class="btn btn-default btn-sm"><i class="fa fa-check fa-fw"></i>Re-open</a>
                {% else %}
                    <a href="{{ path('issuemilestone_close',{ 'id': project.id,'milestoneId': entity.id  }) }}" class="btn btn-default btn-sm"><i class="fa fa-check fa-fw"></i>Close</a>
                {% endif %}
                 <a href="{{ path('issuemilestone_edit',{ 'id': project.id,'milestoneId': entity.id }) }}" class="btn btn-default btn-sm"><i class="fa fa-edit fa-fw"></i>Edit</a>
                 <a href="{{ path('issuemilestone_new',{ 'id': project.id }) }}" class="btn btn-default btn-sm"><i class="fa fa-plus fa-fw"></i>New Milestone</a>
             </div>

        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="heading">
                        <p><small class="text-muted"><i class="fa fa-clock-o"></i> Updated {{ entity.updatedAt|time_ago_in_words }}</small>
                        </p>
                    </div>
                    <p>{{ entity.description | markdown }}</p>
                </div>
                <div class="col-md-6">
                    {% if(closedCount == 0)%}
                        {% set progress = 0 %}
                    {% elseif(openCount == 0)%}
                        {% set progress = 100 %}
                    {% else %}
                        {% set progress = ((openCount / (openCount + closedCount) ) * 100)%}
                    {% endif %}
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="{{progress}}" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: {{progress}}%;">
                          {{progress}}%
                        </div>
                    </div>
                    <ul>
                        <li>
                            <strong>{{progress}}%</strong> complete
                        </li>
                        <li>
                            <strong>{{openCount}}</strong> Open
                        </li>
                        <li>
                            <strong>{{closedCount}}</strong> Closed
                        </li>
                    </ul>
                </div>
            </div>
            
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
             <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-bug fa-fw"></i>Open Issues </h3>
                </div>
                 <div class="box-body">
                      {{ render(controller(
                'VersionControlGitControlBundle:Issues\\IssueMilestone:milestonesIssues',
                { 'id':project.id, 'issueMilestone': entity }
            )) }}
                 </div>
             </div>
        </div>
        <div class="col-md-6">
             <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-bug fa-fw"></i>Closed Issues </h3>
                </div>
                <div class="box-body">
                      {{ render(controller(
                'VersionControlGitControlBundle:Issues\\IssueMilestone:milestonesIssues',
                { 'id':project.id, 'issueMilestone': entity, 'filter': 'closed', pageParameterName:'pageClosed',keywordParamaterName:'keywordclosed' }
            )) }}
                 </div>
             </div>
        </div>
    </div>

{% endblock %}